* Major projects
** Create a literate config using org-mode

* Minor projects
** Update to use elpaca ':wait' recipe keyword
Replace most of the (elpaca-wait) commands scattered throughout with
`:wait` recipes in the relevant packages
** Figure out Mac environment issues
pdf-tools build failed when emacs was launched from the launcher but succeeded
when emacs was launched from the command line. Forgot to copy the message but
some packages weren't available or something.

Similarly emacs says pandoc isn't installed when launched from launcher, but is
fine from command line.

* Package and Custom Settings
** TODO visual-fill-column

- Change defaults in lisp file instead of customize
- enable global visual-fill-column
- figure out the correct column width and amount of extra space on the sides I want

** TODO line number
 - fix the scroll issue with variable pitch fonts caused by when line number for the
   current line has more digits than the other line numbers on screen (it
   usually does because current line is absolute and others are relative)

** TODO Auctex
 - Move customization from customs.el to lang-tex.el
 -see if anything from CDLaTeX is worth using and remap the keybinds to evil format


* Packages to watch
** Packages to try when time is permitting

** Currently bugged
*** nord-theme
Hasn't been updated for emacs 29+ https://github.com/nordtheme/emacs/pulls

(use-package nord-theme)
(use-package nordic-night-theme)



*  Notes On Removed Packages
** desktop
Disabled because it doesn't always play nice with elpaca. It seems it'll resume
and load packages associated with the current buffer before the elpaca init
runs.
** fold-dwim-org
Disabled for many months, name is illustrative but don't recall using it.
** org-contrib
